// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD55aBlFexNet5Pau79dYUZgyZaFTLGgUs',
    appId: '1:145795768666:web:61bfec6c340e93bad2d363',
    messagingSenderId: '145795768666',
    projectId: 'attendance-9a16f',
    authDomain: 'attendance-9a16f.firebaseapp.com',
    storageBucket: 'attendance-9a16f.appspot.com',
    measurementId: 'G-QTRBXNLJNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_IgkNvjkpaqEo_3cWDQfGRBDkWWB_Djs',
    appId: '1:145795768666:android:9fea74f4a072401bd2d363',
    messagingSenderId: '145795768666',
    projectId: 'attendance-9a16f',
    storageBucket: 'attendance-9a16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmKkP4lDc7tqcJydgATOWfr2lIlbiymY',
    appId: '1:145795768666:ios:9fbd49f3f43a28f0d2d363',
    messagingSenderId: '145795768666',
    projectId: 'attendance-9a16f',
    storageBucket: 'attendance-9a16f.appspot.com',
    iosClientId: '145795768666-d4c6tja383rmif69lotsu5u7b2c9dpf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLmKkP4lDc7tqcJydgATOWfr2lIlbiymY',
    appId: '1:145795768666:ios:9fbd49f3f43a28f0d2d363',
    messagingSenderId: '145795768666',
    projectId: 'attendance-9a16f',
    storageBucket: 'attendance-9a16f.appspot.com',
    iosClientId: '145795768666-d4c6tja383rmif69lotsu5u7b2c9dpf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesystem',
  );
}
